server:
  port: 10002
spring:
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        service-name: service1
        instance-id: service1-instance2
        prefer-ip-address: true
        health-check-url: http://${NODE_IP:localhost}:${server.port}/actuator/health1
        health-check-interval: ${HEALTH_CHECK_INTERVAL:10s}

